### ISSUE TITLE
test wrong

### ISSUE THREAD

**Issue by LiYan0306** [ViTAE-Transformer/MTP#29]
How can i fix this problem:
KeyError: 'RVSA_MTP is not in the opencd::model registry. Please check whether the value of `RVSA_MTP` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
![屏幕截图 2024-10-30 094323](https://github.com/user-attachments/assets/cf0f5454-4c6b-42dd-ad80-611473d8c6e8)

**Comment by DotWang** [comment]
@LiYan0306 please registry it manually

**Comment by soniamartinot** [comment]
Hi I'm having a similar issue:

Traceback (most recent call last):
  File "mmdetection/tools/train.py", line 121, in <module>
    main()
  File "mmdetection/tools/train.py", line 117, in main
    runner.train()
  File "/home/smartinot/MTP/mmengine/mmengine/runner/runner.py", line 1733, in train
    self.optim_wrapper = self.build_optim_wrapper(self.optim_wrapper)
  File "/home/smartinot/MTP/mmengine/mmengine/runner/runner.py", line 1114, in build_optim_wrapper
    return build_optim_wrapper(self.model, optim_wrapper)
  File "/home/smartinot/MTP/mmengine/mmengine/optim/optimizer/builder.py", line 205, in build_optim_wrapper
    optim_wrapper_constructor = OPTIM_WRAPPER_CONSTRUCTORS.build(
  File "/home/smartinot/MTP/mmengine/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/smartinot/MTP/mmengine/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'LayerDecayOptimizerConstructor_ViT is not in the mmdet::optimizer constructor registry. Please check whether the value of `LayerDecayOptimizerConstructor_ViT` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'



How do you register "manually" ? Where do I need to copy paste the files that you provided in mmcv_custom ?

Thanks.

**Comment by DotWang** [comment]
@soniamartinot in train.py, we import mmcv_custom
