### ISSUE TITLE
我想请问一下你们tools/train.py可以公开一下吗

### ISSUE THREAD

**Issue by freja-zy** [ViTAE-Transformer/MTP#6]

**Comment by DotWang** [comment]
@freja-zy 这个不用上传的，因为我们在finetune时直接用的openmmlab的框架，你把相应框架装好就有了，然后用我们提供的模型和config文件来跑就行

**Comment by rookie0607** [comment]
> @freja-zy 这个不用上传的，因为我们在finetune时直接用的openmmlab的框架，你把相应框架装好就有了，然后用我们提供的模型和config文件来跑就行


Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 110, in main
    runner = Runner.from_cfg(cfg)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/huangsk/tools/mmdetection/mmdet/models/detectors/faster_rcnn.py", line 20, in __init__
    super().__init__(
  File "/home/huangsk/tools/mmdetection/mmdet/models/detectors/two_stage.py", line 34, in __init__
    self.backbone = MODELS.build(backbone)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'RVSA_MTP_branches is not in the mmdet::model registry. Please check whether the value of `RVSA_MTP_branches` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by DotWang** [comment]
@rookie0607 原始mmdet没有，你自己注册一下啊
